# Generated by Django 3.2.1 on 2022-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField()),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='FSFile',
        ),
    ]
