# Generated by Django 3.2.1 on 2022-11-23 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0002_auto_20221123_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fspath',
            name='id',
        ),
        migrations.AddField(
            model_name='fsfile',
            name='file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='fspath',
            name='path_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fsfile',
            name='file_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fspath',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsapi.fsfile'),
        ),
    ]
