# Generated by Django 3.2.1 on 2022-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0004_alter_fspath_path_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsfile',
            name='file_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fspath',
            name='path_id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
