# Generated by Django 3.2.1 on 2022-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0007_alter_fspath_path_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fspath',
            name='file_id',
            field=models.IntegerField(),
        ),
    ]
