# Generated by Django 3.2.1 on 2022-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0008_alter_fspath_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fspath',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fspath',
            name='path_id',
            field=models.IntegerField(),
        ),
    ]
