# Generated by Django 3.2.1 on 2022-11-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0009_auto_20221123_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fspath',
            name='path_id',
        ),
    ]
