# Generated by Django 3.2.1 on 2022-11-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0010_remove_fspath_path_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FsapiFsfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_uuid', models.UUIDField()),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fsapi_fsfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FsapiFspath',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fsapi_fspath',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FSFile',
        ),
        migrations.DeleteModel(
            name='FSPath',
        ),
    ]
