# Generated by Django 3.2.1 on 2022-11-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0011_auto_20221124_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fsapifsfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fsapifspath',
            options={},
        ),
    ]
