# Generated by Django 3.2.1 on 2022-11-24 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0012_auto_20221124_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fsapifsfile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fsapifspath',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='fsapifspath',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fsapi.fsapifsfile'),
        ),
    ]
