# Generated by Django 3.2.1 on 2022-11-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0013_auto_20221124_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsapifspath',
            name='file_id',
        ),
        migrations.DeleteModel(
            name='FsapiFsfile',
        ),
        migrations.DeleteModel(
            name='FsapiFspath',
        ),
    ]
