# Generated by Django 3.2.1 on 2022-11-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsapi', '0014_auto_20221124_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='FsapiFsfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_uuid', models.UUIDField()),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fsapi_fsfile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FsapiFspath',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('file_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fsapi.fsapifsfile')),
            ],
            options={
                'db_table': 'fsapi_fspath',
                'managed': True,
            },
        ),
    ]
