# Generated by Django 3.2.1 on 2022-11-26 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0016_alter_fsapifsfile_file_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fsfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_uuid', models.UUIDField(default=uuid.uuid4)),
                ('file_name', models.CharField(max_length=255)),
                ('owner_key', models.UUIDField(default=uuid.uuid4)),
                ('file_size', models.BigIntegerField()),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts_deleted', models.DateTimeField()),
                ('user_created', models.CharField(max_length=50)),
                ('user_deleted', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fs_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fspath',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('fs_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fsapi.fsfile')),
            ],
            options={
                'db_table': 'fs_path',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='fsapifspath',
            name='file_id',
        ),
        migrations.DeleteModel(
            name='FsapiFsfile',
        ),
        migrations.DeleteModel(
            name='FsapiFspath',
        ),
    ]
