# Generated by Django 3.2.1 on 2022-11-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0018_rename_fs_file_fspath_fs_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fspath',
            old_name='fs_file_id',
            new_name='fs_file',
        ),
    ]
