# Generated by Django 3.2.1 on 2022-11-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0021_rename_fs_file_fspath_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fspath',
            name='file_part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fspath',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
