# Generated by Django 3.2.1 on 2022-11-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0022_auto_20221127_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fspath',
            name='file_id',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fsapi.fsfile'),
        ),
    ]
