# Generated by Django 3.2.1 on 2022-11-27 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    #replaces = [('fsapi', '0001_initial'), ('fsapi', '0002_auto_20221123_1136'), ('fsapi', '0003_auto_20221123_1832'), ('fsapi', '0004_alter_fspath_path_id'), ('fsapi', '0005_auto_20221123_1836'), ('fsapi', '0006_auto_20221123_1846'), ('fsapi', '0007_alter_fspath_path_id'), ('fsapi', '0008_alter_fspath_file_id'), ('fsapi', '0009_auto_20221123_1852'), ('fsapi', '0010_remove_fspath_path_id'), ('fsapi', '0011_auto_20221124_0959'), ('fsapi', '0012_auto_20221124_1008'), ('fsapi', '0013_auto_20221124_1014'), ('fsapi', '0014_auto_20221124_1024'), ('fsapi', '0015_fsapifsfile_fsapifspath'), ('fsapi', '0016_alter_fsapifsfile_file_uuid'), ('fsapi', '0017_auto_20221126_1656'), ('fsapi', '0018_rename_fs_file_fspath_fs_file_id'), ('fsapi', '0019_rename_fs_file_id_fspath_fs_file'), ('fsapi', '0020_auto_20221126_1706'), ('fsapi', '0021_rename_fs_file_fspath_file_id'), ('fsapi', '0022_auto_20221127_1352'), ('fsapi', '0023_alter_fspath_file_id'), ('fsapi', '0024_remove_fspath_file_id'), ('fsapi', '0025_fspath_file_id')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fsfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_uuid', models.UUIDField(default=uuid.uuid4)),
                ('file_name', models.CharField(max_length=255)),
                ('owner_key', models.UUIDField(default=uuid.uuid4)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('ts_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('ts_deleted', models.DateTimeField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=50, null=True)),
                ('user_deleted', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fs_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fspath',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fsapi.fsfile')),
            ],
            options={
                'db_table': 'fs_path',
                'managed': True,
            },
        ),
    ]
