# Generated by Django 3.2.1 on 2022-12-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0001_squashed_0025_fspath_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fspath',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
