# Generated by Django 3.2.1 on 2022-12-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0003_auto_20221220_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fsfile',
            old_name='owner_key',
            new_name='file_owner_key',
        ),
        migrations.AddField(
            model_name='fsfile',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
