# Generated by Django 3.2.1 on 2022-12-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0004_auto_20221222_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fspath',
            new_name='Fspart',
        ),
        migrations.AlterModelTable(
            name='fspart',
            table='fs_part',
        ),
    ]
