# Generated by Django 4.1.7 on 2023-04-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0005_auto_20221222_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fsfile',
            old_name='file_owner_key',
            new_name='file_master_uuid',
        ),
        migrations.CreateModel(
            name='FsLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(blank=True, max_length=50, null=True)),
                ('log_message', models.CharField(max_length=255)),
                ('user_log', models.CharField(blank=True, max_length=50, null=True)),
                ('ts_log', models.DateTimeField(blank=True, null=True)),
                ('file_id', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fsapi.fsfile')),
            ],
            options={
                'db_table': 'fs_log',
                'managed': True,
            },
        ),
    ]
