# Generated by Django 4.1.7 on 2023-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0006_rename_file_owner_key_fsfile_file_master_uuid_fslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsfile',
            name='ts_cleared',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fslog',
            name='ts_log',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
