# Generated by Django 4.1.7 on 2023-04-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0007_fsfile_ts_cleared_alter_fslog_ts_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fslog',
            options={'managed': True, 'ordering': ['ts_log']},
        ),
        migrations.AlterField(
            model_name='fslog',
            name='file_id',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fsapi.fsfile'),
        ),
    ]
