# Generated by Django 4.1.7 on 2023-04-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapi', '0008_alter_fslog_options_alter_fslog_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fspart',
            name='part_checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
